//todo This would be so cool if you had an ui to make these beat maps, it would make life easier as well.
// I think you could maybe introduce some other libraries as well to make this, but lets keep it for a proof of concept for now
export const noteMaps = {
    song1: [
        {time: 0, type: "blue1"},
        {time: 1, type: "orange1"},
        {time: 2, type: "blue1"},
        {time: 3, type: "orange1"},
    ],
    song2: [
        {time:0 , type: "orange1", key: 'j'},
        {time:1.8 , type: "orange1", key: 'j'},
        {time:4.5 , type: "orange1", key: 'j'},
        {time:7 , type: "orange1", key: 'j'},
        {time:15 , type: "orange1", key: 'j'},
        {time:15.5 , type: "blue1", key: 'k'},
        {time:16.0 , type: "blue1", key: 'k'},
        {time:16.5 , type: "orange1", key: 'j'},
        {time:17.0 , type: "orange1", key: 'j'},
        {time:17.5 , type: "orange1", key: 'j'},
        {time:17.8 , type: "orange1", key: 'j'},
        {time:17.9 , type: "orange1", key: 'j'},
        {time:20.5 , type: "orange1", key: 'j'},
        {time:21 , type: "orange1", key: 'j'},
        {time:21.5 , type: "orange1", key: 'j'},
        {time:22.0 , type: "orange1", key: 'j'},
        {time:22.5 , type: "orange1", key: 'j'},
        {time:23.5 , type: "orange1", key: 'j'},
        {time:24.0 , type: "orange1", key: 'j'},
        {time:24.5 , type: "orange1", key: 'j'},
        {time:25.0 , type: "orange1", key: 'j'},
        {time:26.5 , type: "orange1", key: 'j'},
        {time:26.5 , type: "orange1", key: 'j'},
        {time:27.0 , type: "orange1", key: 'j'},
        {time:27.3 , type: "orange1", key: 'j'},
        {time:27.6 , type: "orange1", key: 'j'},
        {time:28.0 , type: "orange1", key: 'j'},
        {time:28.0 , type: "orange1", key: 'j'},
        {time:29.0 , type: "orange1", key: 'j'},
        {time:30.0 , type: "orange1", key: 'j'},
        {time:31.0 , type: "orange1", key: 'j'},
        {time:32.0 , type: "orange1", key: 'j'},
        {time:33.0 , type: "orange1", key: 'j'},
        {time:34.0 , type: "orange1", key: 'j'},
        {time:35.0 , type: "orange1", key: 'j'},
        {time:35.5 , type: "orange1", key: 'j'},

        //oNE PIECE
        {time:36.5 , type: "orange1", key: 'j'},
        {time:37.0 , type: "orange1", key: 'j'},

        {time:39.5 , type: "orange1", key: 'j'},
        {time:40.0 , type: "orange1", key: 'j'},

        {time:40.2 , type: "orange1", key: 'j'},
        {time:40.4 , type: "orange1", key: 'j'},
        {time:40.6 , type: "orange1", key: 'j'},
        {time:40.8 , type: "orange1", key: 'j'},
        {time:41.0 , type: "orange1", key: 'j'},

        {time:42.0 , type: "orange1", key: 'j'},
        {time:42.4 , type: "blue1", key: 'j'},
        {time:42.8 , type: "orange1", key: 'j'},
        {time:42.2 , type: "blue1", key: 'j'},
        {time:42.6 , type: "orange1", key: 'j'},
        {time:43.0 , type: "blue1", key: 'j'},
        {time:43.4 , type: "orange1", key: 'j'},
        {time:43.8 , type: "blue1", key: 'j'},
        {time:44.2 , type: "orange1", key: 'j'},

        {time:45 , type: "orange1", key: 'j'},
        {time:45.5 , type: "blue1", key: 'j'},
        {time:46 , type: "orange1", key: 'j'},
        {time:46.5 , type: "blue1", key: 'j'},
        {time:47 , type: "orange1", key: 'j'},
        {time:47.5 , type: "blue1", key: 'j'},
        {time:48 , type: "orange1", key: 'j'},
        {time:48.5 , type: "blue1", key: 'j'},
        {time:49 , type: "orange1", key: 'j'},

        {time:49.5 , type: "orange1", key: 'j'},
        {time:50.4 , type: "blue1", key: 'j'},
        {time:50.8 , type: "orange1", key: 'j'},
        {time:51.2 , type: "blue1", key: 'j'},
        {time:53.6 , type: "orange1", key: 'j'},
        {time:54 , type: "blue1", key: 'j'},
        {time:54.4 , type: "orange1", key: 'j'},
        {time:54.8 , type: "blue1", key: 'j'},
        {time:55.2 , type: "orange1", key: 'j'},

        {time:56.6 , type: "blue1", key: 'j'},
        {time:57 , type: "orange1", key: 'j'},

        {time:60 , type: "blue1", key: 'j'},
        {time:61 , type: "orange1", key: 'j'},
        {time:62 , type: "blue1", key: 'j'},
        {time:62.4 , type: "blue1", key: 'j'},
        {time:64.8 , type: "blue1", key: 'j'},
        {time:65.0 , type: "blue1", key: 'j'},

        {time:66 , type: "orange1", key: 'j'},
        {time:66.5 , type: "blue1", key: 'j'},
        {time:67 , type: "orange1", key: 'j'},
        {time:67.5 , type: "blue1", key: 'j'},
        {time:68 , type: "orange1", key: 'j'},
        {time:68.5 , type: "blue1", key: 'j'},
        {time:69 , type: "orange1", key: 'j'},
        {time:69.5 , type: "blue1", key: 'j'},

        {time:70.0 , type: "orange1", key: 'j'},
        {time:72.4 , type: "blue1", key: 'j'},
        {time:72.8 , type: "orange1", key: 'j'},
        {time:72.2 , type: "blue1", key: 'j'},
        {time:72.6 , type: "orange1", key: 'j'},
        {time:73.0 , type: "blue1", key: 'j'},
        {time:73.4 , type: "orange1", key: 'j'},
        {time:73.8 , type: "blue1", key: 'j'},
        {time:74.2 , type: "orange1", key: 'j'},

        {time:76 , type: "orange1", key: 'j'},
        {time:76.5 , type: "blue1", key: 'j'},
        {time:77 , type: "orange1", key: 'j'},
        {time:77.5 , type: "blue1", key: 'j'},
        {time:78 , type: "orange1", key: 'j'},
        {time:78.5 , type: "blue1", key: 'j'},
        {time:79 , type: "orange1", key: 'j'},
        {time:79.5 , type: "blue1", key: 'j'},
        {time:80 , type: "orange1", key: 'j'},

        {time:82.0 , type: "orange1", key: 'j'},
        {time:82.4 , type: "blue1", key: 'j'},
        {time:82.8 , type: "orange1", key: 'j'},
        {time:82.2 , type: "blue1", key: 'j'},
        {time:82.6 , type: "orange1", key: 'j'},
        {time:83.0 , type: "blue1", key: 'j'},
        {time:83.4 , type: "orange1", key: 'j'},
        {time:83.8 , type: "blue1", key: 'j'},
        {time:84.2 , type: "orange1", key: 'j'},

        {time:85.5 , type: "orange1", key: 'j'},
        {time:86.0 , type: "orange1", key: 'j'},
        {time:86.5 , type: "orange1", key: 'j'},
        {time:87.5 , type: "orange1", key: 'j'},
        {time:88.0 , type: "orange1", key: 'j'},
        {time:89.5 , type: "orange1", key: 'j'},
        {time:90.0 , type: "orange1", key: 'j'},
        {time:91.5 , type: "orange1", key: 'j'},
        {time:92.0 , type: "orange1", key: 'j'},
        {time:92.3 , type: "orange1", key: 'j'},
        {time:92.6 , type: "orange1", key: 'j'},
        {time:93.0 , type: "orange1", key: 'j'},
        {time:94.0 , type: "orange1", key: 'j'},
        {time:95.0 , type: "orange1", key: 'j'},
        {time:96.0 , type: "orange1", key: 'j'},


        {time:97.5 , type: "orange1", key: 'j'},
        {time:98.0 , type: "orange1", key: 'j'},
        {time:98.5 , type: "orange1", key: 'j'},
        {time:99 , type: "orange1", key: 'j'},
        {time:100 , type: "orange1", key: 'j'},

        {time:100.2 , type: "orange1", key: 'j'},
        {time:100.4 , type: "blue1", key: 'j'},
        {time:100.6 , type: "orange1", key: 'j'},
        {time:100.8 , type: "blue1", key: 'j'},
        {time:101 , type: "orange1", key: 'j'},
        {time:101.2 , type: "blue1", key: 'j'},
        {time:101.4 , type: "orange1", key: 'j'},
        {time:101.6 , type: "blue1", key: 'j'},
        {time:101.8 , type: "orange1", key: 'j'},
        {time:102 , type: "blue1", key: 'j'},
        {time:102.2 , type: "orange1", key: 'j'},
        {time:102.4 , type: "blue1", key: 'j'},
        {time:102.6 , type: "orange1", key: 'j'},
        {time:102.8 , type: "blue1", key: 'j'},

        //oNE PIECE
        {time:103.0 , type: "orange1", key: 'j'},
        {time:103.3 , type: "orange1", key: 'j'},

        {time:104.0 , type: "orange1", key: 'j'},
        {time:104.3 , type: "orange1", key: 'j'},

    ],

    song3: [
        {time:0 ,type:'orange1'},
        {time:0.8 ,type:'orange1'},
        {time:1.4 ,type:'orange1'},
        {time:2 ,type:'orange1'},
        {time:2.8 ,type:'orange1'},
        {time:3.4 ,type:'orange1'},
        {time:4 ,type:'orange1'},
        {time:4.8 ,type:'orange1'},
        {time:5.4 ,type:'orange1'},
        {time:6 ,type:'orange1'},
        {time:6.4 ,type:'orange1'},
        {time:6.6 ,type:'orange1'},
        {time:7 ,type:'orange1'},

        {time:8 ,type:'orange1'},
        {time:8.4 ,type:'orange1'},
        {time:8.6 ,type:'orange1'},
        {time:9 ,type:'orange1'},

        {time:9.4 ,type:'blue1'},
        {time:9.6 ,type:'blue1'},
        {time:10 ,type:'blue1'},
        {time:10.4 ,type:'blue1'},

        {time:10.6 ,type:'blue1'},
        {time:11 ,type:'blue1'},
        {time:11.4 ,type:'blue1'},
        {time:11.6 ,type:'blue1'},

    ]

}